# Find sunrise and sunset time for year 2019

In [ ]:
import pandas as pd
import requests
from datetime import datetime, timedelta
import pytz
import warnings

# Suppress unnecessary warnings
warnings.filterwarnings("ignore")

# Define the location coordinates for Las Vegas, Nevada, USA
lat = "36.1699"
lng = "-115.1398"

# Create an empty DataFrame to store the results
results_df = pd.DataFrame(columns=["date", "sunrise (local)", "sunset (local)"])

# Define the year and month for which you want sunrise and sunset times
year = 2019
month = 1

# Calculate the number of days in the month
last_day_of_month = (datetime(year, month + 1, 1) - timedelta(days=1)).day

# Function to get sunrise and sunset times in UTC from the API for a given date
def get_sunrise_sunset_utc(date):
    api_url = f"https://api.sunrise-sunset.org/json?lat={lat}&lng={lng}&date={date}&formatted=0"
    response = requests.get(api_url)

    if response.status_code == 200:
        data = response.json()
        sunrise_utc = data["results"]["sunrise"]
        sunset_utc = data["results"]["sunset"]
        return sunrise_utc, sunset_utc
    else:
        print(f"Failed to retrieve data for {date}. Status code: {response.status_code}")
        return None, None

# Function to convert UTC time to local time with timezone and DST handling
def convert_utc_to_local(utc_time, tz_name):
    utc_datetime = datetime.strptime(utc_time, "%Y-%m-%dT%H:%M:%S+00:00")
    utc_timezone = pytz.timezone("UTC")
    local_timezone = pytz.timezone(tz_name)
    utc_datetime = utc_timezone.localize(utc_datetime)
    local_datetime = utc_datetime.astimezone(local_timezone)
    return local_datetime

# Loop through each day in the specified month and fetch sunrise and sunset times
for day in range(1, last_day_of_month + 1):
    date = f"{year}-{month:02d}-{day:02d}"
    sunrise_utc, sunset_utc = get_sunrise_sunset_utc(date)

    if sunrise_utc is not None and sunset_utc is not None:
        # Convert UTC times to local time for Las Vegas, Nevada, USA
        sunrise_local = convert_utc_to_local(sunrise_utc, "America/Los_Angeles")
        sunset_local = convert_utc_to_local(sunset_utc, "America/Los_Angeles")

        # Append the data to the results DataFrame
        results_df = results_df.append({"date": date, "sunrise (local)": sunrise_local, "sunset (local)": sunset_local}, ignore_index=True)

# Convert "sunrise (local)" and "sunset (local)" columns to datetime dtype
results_df["sunrise (local)"] = pd.to_datetime(results_df["sunrise (local)"])
results_df["sunset (local)"] = pd.to_datetime(results_df["sunset (local)"])

# Remove time zone offset (-08:00) from "sunrise (local)" and "sunset (local)" columns
results_df["date"] = results_df["date"].dt.tz_localize(None)
results_df["sunrise (local)"] = results_df["sunrise (local)"].dt.tz_localize(None)
results_df["sunset (local)"] = results_df["sunset (local)"].dt.tz_localize(None)

results_df.to_csv("results_df.csv", index=None, header=None)

# Display the updated DataFrame
results_df

                  date     sunrise (local)      sunset (local)
0  2018-12-31 16:00:00 2019-01-01 06:50:08 2019-01-01 16:38:09
1  2019-01-01 16:00:00 2019-01-02 06:50:17 2019-01-02 16:38:56
2  2019-01-02 16:00:00 2019-01-03 06:50:25 2019-01-03 16:39:44
3  2019-01-03 16:00:00 2019-01-04 06:50:30 2019-01-04 16:40:34
4  2019-01-04 16:00:00 2019-01-05 06:50:33 2019-01-05 16:41:24
5  2019-01-05 16:00:00 2019-01-06 06:50:35 2019-01-06 16:42:16
6  2019-01-06 16:00:00 2019-01-07 06:50:34 2019-01-07 16:43:08
7  2019-01-07 16:00:00 2019-01-08 06:50:32 2019-01-08 16:44:02
8  2019-01-08 16:00:00 2019-01-09 06:50:27 2019-01-09 16:44:56
9  2019-01-09 16:00:00 2019-01-10 06:50:20 2019-01-10 16:45:51
10 2019-01-10 16:00:00 2019-01-11 06:50:12 2019-01-11 16:46:48
11 2019-01-11 16:00:00 2019-01-12 06:50:01 2019-01-12 16:47:44
12 2019-01-12 16:00:00 2019-01-13 06:49:49 2019-01-13 16:48:42
13 2019-01-13 16:00:00 2019-01-14 06:49:35 2019-01-14 16:49:41
14 2019-01-14 16:00:00 2019-01-15 06:49:18 2019-01-15 16:50:40
15 2019-01-15 16:00:00 2019-01-16 06:49:00 2019-01-16 16:51:39
16 2019-01-16 16:00:00 2019-01-17 06:48:40 2019-01-17 16:52:39
17 2019-01-17 16:00:00 2019-01-18 06:48:18 2019-01-18 16:53:40
18 2019-01-18 16:00:00 2019-01-19 06:47:54 2019-01-19 16:54:41
19 2019-01-19 16:00:00 2019-01-20 06:47:28 2019-01-20 16:55:42
20 2019-01-20 16:00:00 2019-01-21 06:47:00 2019-01-21 16:56:44
21 2019-01-21 16:00:00 2019-01-22 06:46:30 2019-01-22 16:57:46
22 2019-01-22 16:00:00 2019-01-23 06:45:59 2019-01-23 16:58:49
23 2019-01-23 16:00:00 2019-01-24 06:45:26 2019-01-24 16:59:51
24 2019-01-24 16:00:00 2019-01-25 06:44:51 2019-01-25 17:00:54
25 2019-01-25 16:00:00 2019-01-26 06:44:14 2019-01-26 17:01:57
26 2019-01-26 16:00:00 2019-01-27 06:43:35 2019-01-27 17:03:01
27 2019-01-27 16:00:00 2019-01-28 06:42:55 2019-01-28 17:04:04
28 2019-01-28 16:00:00 2019-01-29 06:42:13 2019-01-29 17:05:07
29 2019-01-29 16:00:00 2019-01-30 06:41:30 2019-01-30 17:06:11
30 2019-01-30 16:00:00 2019-01-31 06:40:44 2019-01-31 17:07:14

# only time for year

In [ ]:
import pandas as pd
import requests
from datetime import datetime, timedelta
import pytz
import warnings

# Suppress unnecessary warnings
warnings.filterwarnings("ignore")

# Define the location coordinates for Las Vegas, Nevada, USA
lat = "36.1699"
lng = "-115.1398"

# Create an empty DataFrame to store the results
results_df = pd.DataFrame(columns=["date", "sunrise (local)", "sunset (local)"])

# Define the year for which you want sunrise and sunset times
year = 2019

# Function to get sunrise and sunset times in UTC from the API for a given date
def get_sunrise_sunset_utc(date):
    api_url = f"https://api.sunrise-sunset.org/json?lat={lat}&lng={lng}&date={date}&formatted=0"
    response = requests.get(api_url)

    if response.status_code == 200:
        data = response.json()
        sunrise_utc = data["results"]["sunrise"]
        sunset_utc = data["results"]["sunset"]
        return sunrise_utc, sunset_utc
    else:
        print(f"Failed to retrieve data for {date}. Status code: {response.status_code}")
        return None, None

# Function to convert UTC time to local time with timezone and DST handling
def convert_utc_to_local(utc_time, tz_name):
    utc_datetime = datetime.strptime(utc_time, "%Y-%m-%dT%H:%M:%S+00:00")
    utc_timezone = pytz.timezone("UTC")
    local_timezone = pytz.timezone(tz_name)
    utc_datetime = utc_timezone.localize(utc_datetime)
    local_datetime = utc_datetime.astimezone(local_timezone)
    return local_datetime

# Loop through each day in the specified year and fetch sunrise and sunset times
start_date = datetime(year, 1, 1)
end_date = datetime(year, 12, 31)

current_date = start_date
while current_date <= end_date:
    date = current_date.strftime("%Y-%m-%d")
    sunrise_utc, sunset_utc = get_sunrise_sunset_utc(date)

    if sunrise_utc is not None and sunset_utc is not None:
        # Convert UTC times to local time for Las Vegas, Nevada, USA
        sunrise_local = convert_utc_to_local(sunrise_utc, "America/Los_Angeles")
        sunset_local = convert_utc_to_local(sunset_utc, "America/Los_Angeles")

        # Append the data to the results DataFrame
        results_df = results_df.append({"date": date, "sunrise (local)": sunrise_local, "sunset (local)": sunset_local}, ignore_index=True)

    # Move to the next day
    current_date += timedelta(days=1)

# Convert "sunrise (local)" and "sunset (local)" columns to datetime dtype
results_df["date"] = pd.to_datetime(results_df["date"])
results_df["sunrise (local)"] = pd.to_datetime(results_df["sunrise (local)"])
results_df["sunset (local)"] = pd.to_datetime(results_df["sunset (local)"])

# Display the DataFrame with sunrise and sunset times in local time with timezone and DST handling
print(results_df)

# Remove time zone offset (-08:00) from "sunrise (local)" and "sunset (local)" columns
results_df["sunrise (local)"] = results_df["sunrise (local)"].dt.tz_localize(None)
results_df["sunset (local)"] = results_df["sunset (local)"].dt.tz_localize(None)

# Display the updated DataFrame
print(results_df)

                         date           sunrise (local)  \
0   2018-12-31 16:00:00-08:00 2019-01-01 06:50:08-08:00
1   2019-01-01 16:00:00-08:00 2019-01-02 06:50:17-08:00
2   2019-01-02 16:00:00-08:00 2019-01-03 06:50:25-08:00
3   2019-01-03 16:00:00-08:00 2019-01-04 06:50:30-08:00
4   2019-01-04 16:00:00-08:00 2019-01-05 06:50:33-08:00
..                        ...                       ...
360 2019-12-26 16:00:00-08:00 2019-12-27 06:48:49-08:00
361 2019-12-27 16:00:00-08:00 2019-12-28 06:49:08-08:00
362 2019-12-28 16:00:00-08:00 2019-12-29 06:49:25-08:00
363 2019-12-29 16:00:00-08:00 2019-12-30 06:49:41-08:00
364 2019-12-30 16:00:00-08:00 2019-12-31 06:49:54-08:00

               sunset (local)
0   2019-01-01 16:38:09-08:00
1   2019-01-02 16:38:56-08:00
2   2019-01-03 16:39:44-08:00
3   2019-01-04 16:40:34-08:00
4   2019-01-05 16:41:24-08:00
..                        ...
360 2019-12-27 16:34:25-08:00
361 2019-12-28 16:35:05-08:00
362 2019-12-29 16:35:46-08:00
363 2019-12-30 16:36:29-08:00
364 2019-12-31 16:37:13-08:00

[365 rows x 3 columns]
                         date     sunrise (local)      sunset (local)
0   2018-12-31 16:00:00-08:00 2019-01-01 06:50:08 2019-01-01 16:38:09
1   2019-01-01 16:00:00-08:00 2019-01-02 06:50:17 2019-01-02 16:38:56
2   2019-01-02 16:00:00-08:00 2019-01-03 06:50:25 2019-01-03 16:39:44
3   2019-01-03 16:00:00-08:00 2019-01-04 06:50:30 2019-01-04 16:40:34
4   2019-01-04 16:00:00-08:00 2019-01-05 06:50:33 2019-01-05 16:41:24
..                        ...                 ...                 ...
360 2019-12-26 16:00:00-08:00 2019-12-27 06:48:49 2019-12-27 16:34:25
361 2019-12-27 16:00:00-08:00 2019-12-28 06:49:08 2019-12-28 16:35:05
362 2019-12-28 16:00:00-08:00 2019-12-29 06:49:25 2019-12-29 16:35:46
363 2019-12-29 16:00:00-08:00 2019-12-30 06:49:41 2019-12-30 16:36:29
364 2019-12-30 16:00:00-08:00 2019-12-31 06:49:54 2019-12-31 16:37:13

[365 rows x 3 columns]

In [ ]:
results_df["date"] = results_df["date"].dt.tz_localize(None)
results_df

                   date     sunrise (local)      sunset (local)
0   2018-12-31 16:00:00 2019-01-01 06:50:08 2019-01-01 16:38:09
1   2019-01-01 16:00:00 2019-01-02 06:50:17 2019-01-02 16:38:56
2   2019-01-02 16:00:00 2019-01-03 06:50:25 2019-01-03 16:39:44
3   2019-01-03 16:00:00 2019-01-04 06:50:30 2019-01-04 16:40:34
4   2019-01-04 16:00:00 2019-01-05 06:50:33 2019-01-05 16:41:24
..                  ...                 ...                 ...
360 2019-12-26 16:00:00 2019-12-27 06:48:49 2019-12-27 16:34:25
361 2019-12-27 16:00:00 2019-12-28 06:49:08 2019-12-28 16:35:05
362 2019-12-28 16:00:00 2019-12-29 06:49:25 2019-12-29 16:35:46
363 2019-12-29 16:00:00 2019-12-30 06:49:41 2019-12-30 16:36:29
364 2019-12-30 16:00:00 2019-12-31 06:49:54 2019-12-31 16:37:13

[365 rows x 3 columns]

# Final working

In [ ]:
import pandas as pd
import requests
from datetime import datetime
import pytz
import warnings
from multiprocessing import Pool

# Suppress unnecessary warnings
warnings.filterwarnings("ignore")

# Define the location coordinates for Las Vegas, Nevada, USA
lat = "36.1699"
lng = "-115.1398"

# Load your 2019 weather dataset (replace with your actual file path)
df_19 = pd.read_csv("/content/LA_Nevada_2019_20.csv")
df_19 = df_19[df_19['Year'] == 2019]

# Combine 'Year', 'Month', 'Day', 'Hour', and 'Minute' columns into a single datetime column
df_19['Datetime'] = pd.to_datetime(df_19[['Year', 'Month', 'Day', 'Hour', 'Minute']])

# Filter out rows with time between 21:00 and 04:00
df_19 = df_19[(df_19['Datetime'].dt.hour >= 4) & (df_19['Datetime'].dt.hour < 21)]

# Define a function to get sunrise and sunset times in UTC from the API for a given date
def get_sunrise_sunset_utc(date):
    api_url = f"https://api.sunrise-sunset.org/json?lat={lat}&lng={lng}&date={date}&formatted=0"
    response = requests.get(api_url)

    if response.status_code == 200:
        data = response.json()
        sunrise_utc = data["results"]["sunrise"]
        sunset_utc = data["results"]["sunset"]
        return sunrise_utc, sunset_utc
    else:
        print(f"Failed to retrieve data for {date}. Status code: {response.status_code}")
        return None, None  # Return None for both sunrise and sunset

# Function to convert UTC time to local time with timezone and DST handling
def convert_utc_to_local(utc_time, tz_name):
    try:
        utc_datetime = datetime.strptime(utc_time, "%Y-%m-%dT%H:%M:%S+00:00")
        utc_timezone = pytz.timezone("UTC")
        local_timezone = pytz.timezone(tz_name)
        utc_datetime = utc_timezone.localize(utc_datetime)
        local_datetime = utc_datetime.astimezone(local_timezone)
        return local_datetime
    except pytz.exceptions.NonExistentTimeError:
        # Handle the case where the time doesn't exist due to DST changes
        # You can choose to skip or handle this timestamp as needed
        return None

# Define the batch size for multiprocessing
batch_size = 1000

# Define a function to process a batch of data
def process_batch(batch_df):
    results = []
    for index, row in batch_df.iterrows():
        date = row['Datetime'].strftime("%Y-%m-%d")
        sunrise_utc, sunset_utc = get_sunrise_sunset_utc(date)

        if sunrise_utc is not None and sunset_utc is not None:
            sunrise_local = convert_utc_to_local(sunrise_utc, "America/Los_Angeles")
            sunset_local = convert_utc_to_local(sunset_utc, "America/Los_Angeles")
            row_datetime = row['Datetime'].replace(tzinfo=pytz.timezone("America/Los_Angeles"))

            if sunrise_local <= row_datetime <= sunset_local:
                results.append(True)
            else:
                results.append(False)

    batch_df['is_day'] = results
    return batch_df

# Split the DataFrame into batches
batches = [df_19[i:i+batch_size] for i in range(0, len(df_19), batch_size)]

# Create a Pool of workers to process batches concurrently
with Pool(processes=5) as pool:
    results = pool.map(process_batch, batches)

# Concatenate the processed batches back into a single DataFrame
final_df = pd.concat(results)

# Print the final DataFrame with the 'is_day' column
print(final_df.head())

    Year  Month  Day  Hour  Minute  DHI  DNI  GHI  Relative Humidity  \
24  2019      1    1     4       0    0    0    0              37.40
25  2019      1    1     4      10    0    0    0              37.40
26  2019      1    1     4      20    0    0    0              37.40
27  2019      1    1     4      30    0    0    0              37.40
28  2019      1    1     4      40    0    0    0              35.98

    Solar Zenith Angle  Temperature  is_day            Datetime
24              123.81         -1.7   False 2019-01-01 04:00:00
25              121.81         -1.7   False 2019-01-01 04:10:00
26              119.80         -1.7   False 2019-01-01 04:20:00
27              117.81         -1.7   False 2019-01-01 04:30:00
28              115.82         -1.8   False 2019-01-01 04:40:00

In [ ]:
final_df

,Year,Month,Day,Hour,Minute,DHI,DNI,GHI,Relative Humidity,Solar Zenith Angle,Temperature,is_day,Datetime
24,2019,1,1,4,0,0,0,0,37.40,123.81,-1.7,False,2019-01-01 04:00:00
25,2019,1,1,4,10,0,0,0,37.40,121.81,-1.7,False,2019-01-01 04:10:00
26,2019,1,1,4,20,0,0,0,37.40,119.80,-1.7,False,2019-01-01 04:20:00
27,2019,1,1,4,30,0,0,0,37.40,117.81,-1.7,False,2019-01-01 04:30:00
28,2019,1,1,4,40,0,0,0,35.98,115.82,-1.8,False,2019-01-01 04:40:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
52537,2019,12,31,20,10,0,0,0,39.35,132.31,0.7,False,2019-12-31 20:10:00
52538,2019,12,31,20,20,0,0,0,39.63,134.32,0.6,False,2019-12-31 20:20:00
52539,2019,12,31,20,30,0,0,0,39.92,136.34,0.5,False,2019-12-31 20:30:00
52540,2019,12,31,20,40,0,0,0,37.84,138.35,0.4,False,2019-12-31 20:40:00
52541,2019,12,31,20,50,0,0,0,38.12,140.36,0.3,False,2019-12-31 20:50:00

In [ ]:
final_df.to_csv('LA_Nevada_19_20.csv',index=None)